source 'https://rubygems.org'
ruby '1.9.3'

gem 'jekyll', '~> 1.0.3'
gem 'sass', '~> 3.2.9'
gem 'haml', '~> 4.0.3'
gem 'compass', '~> 0.12.2'
gem 'RedCloth', '~> 4.2.9'
gem 'heroku', '~> 2.28.7'
gem 'rack-jekyll', '~> 0.4.1'
gem 'unicorn', '~> 4.3.1'
gem 'rdiscount', :git => 'https://github.com/sunaku/rdiscount.git'
gem 'zurb-foundation', '~> 4.3.0'
gem 'foreman', '~> 0.63.0'
gem 'gemoji', '~> 1.4.0'
